Author:
    type: object
    config:
        description: "A book writer"
        fields:
            id:
                type: "Int!"
                description: "The author unique ID"
            lastName:
                type: "String!"
                description: "The last (family) name of the author, as Doe in John Doe"
            firstName:
                type: "String!"
                description: "The first name of the author, as John in John Doe"
            birthDate:
                type: "DateTime"
                description: "The author's date of birth"