Book:
    type: object
    config:
        description: "A book"
        fields:
            id:
                type: "Int!"
                description: "The book unique ID"
            title:
                type: "String!"
                description: "The book title"
            releaseDate:
                type: "DateTime"
                description: "The release date of the book"
            type:
                type: "String"
                description: "The type of book (sci-fi, ...)"
            price:
                type: "Float"
                description: "The book's price, in euros"
            author:
                type: "Author!"
                description: "The book writer"