Mutation:
    type: object
    config:
        fields:
            authorInput:
                type: AuthorInputPayload!
                args:
                    input:
                        type: AuthorInput
                resolve: "@=resolver('AuthorInput', [args])"
            bookInput:
                type: BookInputPayload!
                args:
                    input:
                        type: BookInput
                resolve: "@=resolver('BookInput', [args])"
            userInput:
                type: UserInputPayload!
                args:
                    input:
                        type: UserInput
                resolve: "@=resolver('UserInput', [args])"